import os as _os, tempfile as _tf
_HERE = _os.path.dirname(_os.path.abspath(__file__)); _APP = _os.path.abspath(_os.path.join(_HERE, "..", ".."))
_OUT = _os.path.join(_tf.gettempdir(), "repsmith-shots"); _os.makedirs(_OUT, exist_ok=True)
import json, subprocess, sys, time, os
from playwright.sync_api import sync_playwright

APP = _APP
SHOTS = _OUT
os.makedirs(SHOTS, exist_ok=True)
srv = subprocess.Popen([sys.executable, "-m", "http.server", "8765", "-d", APP], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(1)
errors = []
ok = lambda m: print("PASS", m)

def click(page, sel, **kw):
    page.locator(sel, **kw).first.click()
    page.wait_for_timeout(120)

try:
    with sync_playwright() as p:
        b = p.chromium.launch()
        ctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2, locale="pl-PL", has_touch=True)
        page = ctx.new_page()
        page.on("pageerror", lambda e: errors.append(str(e)))
        page.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)
        page.goto("http://localhost:8765/index.html")
        page.wait_for_selector("text=Dziś trening")
        page.screenshot(path=f"{SHOTS}/01-empty.png"); ok("empty state")

        # create plan
        click(page, "button[data-a=nav][data-v=plans]"); click(page, "button[data-a=new-plan]")
        click(page, "button[data-a=np-create][data-v=advanced]")
        page.wait_for_selector("#pickq")
        click(page, "button[data-a=sheet-close]")
        page.fill("#pn", "Grind 2x")
        page.locator("[data-f=day-name]").first.fill("Dzień A · Przysiad")
        click(page, "button[data-a=day-add-ex]")
        page.fill("#pickq", "squat")
        page.wait_for_timeout(150)
        click(page, "#picklist button[data-v=squat]")
        # item sheet opens: switch to top set + backoff
        click(page, "button[data-a=item-method][data-v=P1]")
        click(page, "button[data-a=tg-mode][data-v=fixed]"); page.fill("#tg-lo", "3")
        click(page, "button[data-a=item-rpe]"); click(page, ".rpe-opt[data-v='8']")
        page.fill("#it-backoffSets", "2")
        click(page, "button[data-a=bk-mode][data-v=fixed]"); page.fill("#tg-bklo", "5")
        click(page, "button[data-a=item-save]")
        for q, idv in (("bayes", "bayesian-curl"), ("chest-supported t", "chest-supported-t-bar-row"), ("one-arm pre", "one-arm-preacher-curl")):
            click(page, "button[data-a=day-add-ex]")
            page.fill("#pickq", q); page.wait_for_timeout(150)
            click(page, f"#picklist button[data-v={idv}]")
            click(page, "button[data-a=item-save]")
        click(page, "button[data-a=day-add-ex]")
        page.fill("#pickq", "farmer"); page.wait_for_timeout(150)
        click(page, "#picklist button[data-v=farmer-s-carry]")
        lbl = page.locator(".tg-block > label").first.inner_text()
        assert lbl == "Dystans (m)", lbl; ok("plan editor: farmer's carry asks for distance")
        click(page, "button[data-a=item-save]")
        assert "3 × 30 m" in page.locator("main").inner_text(); ok("plan shows 3 × 30 m")
        click(page, "button[data-a=plan-add-day]")
        page.screenshot(path=f"{SHOTS}/02-plan.png", full_page=True); ok("plan built")
        click(page, "button[data-a=nav][data-v=plans] >> nth=-1")
        click(page, "button[data-a=nav][data-v=today]")
        page.wait_for_selector("text=Dzień A · Przysiad")
        page.screenshot(path=f"{SHOTS}/03-today.png"); ok("today shows next day")

        # start workout
        click(page, "button[data-a=start-day]")
        page.wait_for_selector(".ex-card")
        n_cards = page.locator(".ex-card").count()
        assert n_cards == 5, n_cards
        sets_first = page.locator(".ex-card").first.locator(".set").count()
        assert sets_first == 3, sets_first  # top + 2 backoff
        uni_sets = page.locator(".ex-card").nth(1).locator(".set").count()
        assert uni_sets == 6, uni_sets  # bayesian 3 sets x L/R
        ok("session from template: top+backoff and L/R sets")

        # log top set 140x3 @8
        top = page.locator(".ex-card").first.locator(".set").first
        w = top.locator("input[data-k=weight]"); r = top.locator("input[data-k=reps]")
        w.click(); w.press_sequentially(" 1 7 , 5,2.x "); assert w.input_value() == "17,52", w.input_value(); ok("weight: no spaces, one separator, no letters")
        w.fill(""); w.press_sequentially("17.5"); assert w.input_value() == "17.5"; ok("weight accepts a dot")
        r.click(); r.press_sequentially(" 1 2,5.x"); assert r.input_value() == "125", r.input_value(); ok("reps: digits only")
        assert r.get_attribute("inputmode") == "numeric"; ok("reps use numeric keyboard")
        w.fill(""); r.fill("")
        top.locator("input[data-k=weight]").fill("140")
        top.locator("input[data-k=reps]").fill("3")
        top.locator("button.rpe-btn").click(); page.wait_for_timeout(100)
        assert page.locator(".rpe-opt").count() == 10; ok("RPE picker shows 10 options 5-10")
        page.locator(".rpe-opt[data-v='8']").click(); page.wait_for_timeout(100)
        top = page.locator(".ex-card").first.locator(".set").first
        assert top.locator("button.rpe-btn").inner_text() == "8"; ok("RPE 8 picked")
        top.locator("button.check").click(); page.wait_for_timeout(200)
        assert page.locator("#timer").is_visible(); ok("rest timer starts")
        bo_ph = page.locator(".ex-card").first.locator(".set").nth(1).locator("input[data-k=weight]").get_attribute("placeholder")
        assert bo_ph == "125", bo_ph  # 140*0.9 = 126 -> rounded to 2.5 = 125
        ok(f"backoff suggestion {bo_ph} kg")
        t0 = page.locator("#tbig").inner_text()
        click(page, "button[data-a=timer-adj][data-v='15']")
        t1 = page.locator("#tbig").inner_text()
        click(page, "button[data-a=timer-adj][data-v='-15']")
        print("timer", t0, "+15 ->", t1)
        # backoff done from placeholder
        page.locator(".ex-card").first.locator(".set").nth(1).locator("button.check").click(); page.wait_for_timeout(150)
        page.screenshot(path=f"{SHOTS}/04-workout.png"); ok("backoff accepted from placeholder")
        click(page, "button[data-a=timer-skip]")
        assert page.locator("#timer").count() == 0; ok("timer skip")

        # note on exercise
        click(page, ".ex-card >> nth=0 >> button[data-a=note]")
        page.fill("#notearea", "Stopy szerzej, pas od 120 kg")
        click(page, "button[data-a=note-save]")
        assert "pas od 120" in page.locator(".ex-card").first.inner_text(); ok("note saved")

        # swap chest-supported t-bar row
        click(page, ".ex-card >> nth=2 >> button[data-a=subs]")
        opts = page.locator(".sub-opt .n").all_inner_texts()
        print("subs for chest-supported T-bar row:", opts)
        assert len(opts) == 2
        page.locator(".sub-opt").first.click(); page.wait_for_timeout(150)
        assert opts[0].upper() in page.locator(".ex-card").nth(2).locator(".ex-name").inner_text().upper(); ok("swap works")

        r = page.evaluate("[window.Repsmith.e1rm(120,5,8), window.Repsmith.e1rm(120,5,6), window.Repsmith.e1rm(120,5,6.5), window.Repsmith.e1rm(100,1,10), window.Repsmith.e1rm(100,13,8), window.Repsmith.rpePct(5,8.3)]")
        print("e1rm 120x5@8, @6, @6.5, 100x1@10, 100x13@8, pct(5,8.3):", r)
        assert abs(r[0]-147.97) < 0.05 and abs(r[1]-155.04) < 0.05 and r[1] == r[2] and r[3] == 100 and r[4] is None and r[5] == 82.4; ok("e1RM from RPE table")
        page.locator(".ex-card").nth(0).locator(".set").nth(2).locator("button.rpe-btn").click(); page.wait_for_timeout(100)
        d = page.locator(".rpe-opt[data-v='8.5'] .d").inner_text(); print("desc 8.5:", d)
        assert "1–2" in d; ok("RPE descriptions shown")
        page.screenshot(path=f"{SHOTS}/08-rpe.png")
        page.locator("button[data-a=rpe-set][data-v='']").click(); page.wait_for_timeout(100)
        click(page, "button[data-a=rename]")
        page.fill("#rn", "Nogi ciężko"); click(page, "button[data-a=rename-save]")
        assert "NOGI CIĘŻKO" in page.locator(".wk-title").inner_text().upper(); ok("rename workout")
        # reload mid-workout -> session restored
        page.wait_for_timeout(600)
        page.reload(); page.wait_for_selector(".ex-card")
        assert page.locator(".ex-card").first.locator(".set.done").count() == 2; ok("active workout survives reload")

        # finish
        click(page, "button[data-a=finish] >> nth=0")
        click(page, "button[data-a=diff-pick][data-v='8']")
        page.fill("#sum-note", "Dobra sesja, kolano OK")
        click(page, "button[data-a=summary-save]")
        page.wait_for_selector("text=Czas")
        txt = page.locator("main").inner_text()
        assert "Dobra sesja" in txt and "8" in txt; ok("summary saved with difficulty and note")
        page.screenshot(path=f"{SHOTS}/05-summary.png", full_page=True); ok("finish -> summary")

        # second workout same day -> previous values shown
        click(page, "button[data-a=nav][data-v=today]")
        page.wait_for_timeout(200)
        today_txt = page.locator("main").inner_text()
        assert "Dzień B" in today_txt, today_txt[:200]; ok("rotation moves to next day")
        click(page, "button[data-a=pick-day] >> text=Dzień A · Przysiad")
        click(page, "button[data-a=start-day]")
        prev = page.locator(".ex-card").first.locator(".set .prev").first.inner_text()
        assert prev.startswith("140"), prev; ok(f"previous shown: {prev}")
        ph = page.locator(".ex-card").first.locator(".set").first.locator("input[data-k=weight]").get_attribute("placeholder")
        assert ph == "145", ph; ok("P1: top set 140x3 @8 on target -> next top 145 (+5 kg lower body)")
        sug = page.locator(".ex-card").first.locator(".sug").inner_text()
        assert "145 kg" in sug and "+5 kg" in sug, sug; ok(f"suggestion line: {sug}")
        top = page.locator(".ex-card").first.locator(".set").first
        top.locator("input[data-k=weight]").fill("145"); top.locator("input[data-k=reps]").fill("2")
        top.locator("button.check").click(); page.wait_for_timeout(200)
        toast_txt = page.locator("#toast").inner_text()
        print("toast:", toast_txt)
        assert "ciężar" in toast_txt and "e1RM" not in toast_txt; ok("PR: 145x2 (no RPE = RPE10, e1RM 151.8) beats weight but not e1RM 162.2 from 140x3@8")
        assert page.locator(".ex-card").first.locator(".pr-badge").count() == 1; ok("PR badge on set")
        click(page, "button[data-a=finish] >> nth=0"); click(page, "button[data-a=summary-save]")
        click(page, "button[data-a=nav][data-v=history]")
        assert page.locator(".diff-badge").count() == 1 and page.locator(".pr-badge").count() == 1; ok("history: difficulty and PR count visible")
        click(page, "button[data-a=nav][data-v=library]")
        page.fill("#libq", "przysiad ze sztang"); page.wait_for_timeout(150)
        click(page, "#liblist button[data-v=squat]")
        rec = page.locator(".sheet").inner_text()
        print("records:", rec.split("REKORDY")[-1][:200].replace(chr(10)," | ") if "REKORDY" in rec else rec[:300])
        assert "145 kg" in rec; ok("records in exercise detail")
        click(page, "button[data-a=sheet-close]")

        # history + export/import roundtrip
        click(page, "button[data-a=nav][data-v=history]")
        assert page.locator("button[data-a=open-session]").count() == 2; ok("history list")
        backup = page.evaluate("JSON.stringify({app:'repsmith',schema:1,settings:window.Repsmith.S.settings,templates:window.Repsmith.S.templates,sessions:window.Repsmith.S.sessions,notes:window.Repsmith.S.notes,customExercises:window.Repsmith.S.customExercises,active:null})")
        click(page, "button[data-a=settings]")
        with page.expect_download() as dl:
            click(page, "button[data-a=export]")
        path = dl.value.path(); data = json.load(open(path))
        assert data["app"] == "repsmith" and len(data["sessions"]) == 2; ok("export downloads backup")
        click(page, "button[data-a=sheet-close]")

        # custom exercise
        click(page, "button[data-a=nav][data-v=library]")
        click(page, "button[data-a=custom-new]")
        page.fill("#cx-pl", "Wiosło na maszynie Gym80"); page.select_option("#cx-pat", "HPULL"); page.select_option("#cx-eq", "MACH")
        click(page, "button[data-a=cx-m][data-f2=primary][data-v=UB]")
        click(page, "button[data-a=cx-save]")
        page.fill("#libq", "gym80"); page.wait_for_timeout(150)
        assert page.locator("#liblist button").count() == 1; ok("custom exercise added and searchable")
        page.screenshot(path=f"{SHOTS}/06-library.png")

        # import into a fresh context
        ctx2 = b.new_context(viewport={"width": 390, "height": 844}, locale="pl-PL")
        p2 = ctx2.new_page(); p2.on("pageerror", lambda e: errors.append(str(e)))
        p2.goto("http://localhost:8765/index.html"); p2.wait_for_selector("text=Dziś trening")
        p2.locator("button[data-a=settings]").click()
        p2.set_input_files("#importfile", path); p2.wait_for_timeout(200)
        p2.locator("button[data-a=confirm-yes]").click(); p2.wait_for_timeout(300)
        assert "Dzień" in p2.locator("main").inner_text(); ok("import restores data in a fresh browser")

        # ---------- v0.5 ----------
        # progress: strength
        click(page, "button[data-a=nav][data-v=progress]")
        txt = page.locator("main").inner_text()
        assert "PRZYSIAD ZE SZTANG" in txt.upper(); ok("progress opens on most-logged exercise")
        assert page.locator("svg[data-a=chart-tap]").count() == 1
        page.locator("svg[data-a=chart-tap]").click(position={"x": 300, "y": 60}); page.wait_for_timeout(100)
        tip = page.locator("#c-e1rm-tip").inner_text(); print("chart tip:", tip)
        assert "kg" in tip; ok("e1RM chart tap shows value")
        assert "145" in page.locator("main").inner_text(); ok("PR list shows 145 kg set")
        vol = page.locator(".vol-row").all_inner_texts(); print("volume:", [v.replace(chr(10), " ") for v in vol[:4]])
        assert len(vol) >= 3; ok("weekly volume per muscle")
        page.screenshot(path=f"{SHOTS}/09-progress.png", full_page=True)
        # body: two measurements
        click(page, "button[data-a=prog-tab][data-v=body]")
        click(page, "button[data-a=m-new]")
        page.fill("#m-weight", "83,4"); page.fill("#m-waist", "86")
        import datetime as _dt
        page.fill("#m-date", (_dt.date.today() - _dt.timedelta(days=10)).isoformat())
        click(page, "button[data-a=m-save]")
        click(page, "button[data-a=m-new]")
        page.fill("#m-weight", "82"); page.fill("#m-waist", "84,5")
        click(page, "button[data-a=m-save]")
        btxt = page.locator("main").inner_text()
        assert "82" in btxt and page.locator(".legend").count() == 1; ok("body: weight chart with 7-day average + legend")
        assert "86 → 84,5" in btxt; ok("body: start → now summary for waist")
        click(page, "button[data-a=m-sides][data-v=arm]")
        click(page, "button[data-a=m-new]")
        assert page.locator("#m-armL").count() == 1 and page.locator("#m-armR").count() == 1; ok("L/R toggle for arm")
        click(page, "button[data-a=sheet-close]")
        page.screenshot(path=f"{SHOTS}/10-body.png", full_page=True)
        bw = page.evaluate("window.Repsmith.bodyweightAt(Date.now())"); assert bw == 82, bw; ok("body weight feeds bodyweight lifts")
        # bodyweight exercise PRs (GHR)
        click(page, "button[data-a=nav][data-v=today]")
        click(page, "button[data-a=start-free]")
        click(page, "button[data-a=session-add-ex]"); page.fill("#pickq", "glute ham"); page.wait_for_timeout(150)
        click(page, "#picklist button[data-v=glute-ham-raise]")
        assert "1. RAZ" in page.locator(".ex-card").first.inner_text().upper(); ok("first-time baseline tag")
        st = page.locator(".ex-card").first.locator(".set").first
        st.locator("input[data-k=weight]").fill("12"); st.locator("input[data-k=reps]").fill("4"); st.locator("button.check").click(); page.wait_for_timeout(150)
        click(page, "button[data-a=timer-skip]")
        click(page, "button[data-a=finish] >> nth=0"); click(page, "button[data-a=summary-save]")
        click(page, "button[data-a=nav][data-v=today]")
        click(page, "button[data-a=start-free]")
        click(page, "button[data-a=session-add-ex]"); page.fill("#pickq", "glute ham"); page.wait_for_timeout(150)
        click(page, "#picklist button[data-v=glute-ham-raise]")
        st = page.locator(".ex-card").first.locator(".set").first
        st.locator("input[data-k=weight]").fill("50"); st.locator("input[data-k=reps]").fill("6"); st.locator("button.check").click(); page.wait_for_timeout(200)
        tt = page.locator("#toast").inner_text(); print("GHR toast:", tt)
        assert "ciężar" in tt and "objętość" in tt; ok("bodyweight lift PR: BW 82 + 50 kg")
        click(page, "button[data-a=timer-skip]")
        click(page, "button[data-a=discard]"); click(page, "button[data-a=confirm-yes]")
        # RPE picker in plan editor
        click(page, "button[data-a=nav][data-v=plans]")
        click(page, "button[data-a=open-plan]")
        click(page, "button[data-a=edit-item] >> nth=1")
        click(page, "button[data-a=item-rpe]")
        click(page, ".rpe-opt[data-v='8.5']")
        assert page.locator("button[data-a=item-rpe]").inner_text().strip() == "8,5"
        click(page, "button[data-a=item-save]")
        assert "@8,5" in page.locator("main").inner_text(); ok("RPE picker in plan editor")
        click(page, "button[data-a=nav][data-v=plans] >> nth=-1")

        # ---------- v0.5.1 ----------
        click(page, "button[data-a=nav][data-v=progress]"); click(page, "button[data-a=prog-tab][data-v=strength]")
        bb = page.locator("button[data-a=prog-week][data-v='1']").bounding_box()
        assert bb["x"] + bb["width"] <= 390, bb; ok("week chips fit on screen")
        click(page, "button[data-a=nav][data-v=history]")
        click(page, "button[data-a=open-session] >> nth=-1")
        src_n = page.locator(".card .row").count()
        click(page, "button[data-a=repeat]")
        page.wait_for_selector(".ex-card")
        assert page.locator(".ex-card").count() == src_n and page.locator(".set.done").count() == 0; ok("repeat workout copies exercises with empty sets")
        prev = page.locator(".ex-card").first.locator(".set .prev").first.inner_text(); print("repeat prev:", prev)
        assert prev != "–"; ok("repeat shows previous results as hints")
        click(page, "button[data-a=discard]"); click(page, "button[data-a=confirm-yes]")
        click(page, "button[data-a=settings]")
        assert "Adrian Drożdżyński" in page.locator(".sheet").inner_text(); ok("author credit in settings")
        click(page, "button[data-a=sheet-close]")

        # ---------- v0.5.3 filters ----------
        click(page, "button[data-a=nav][data-v=today]"); click(page, "button[data-a=start-free]")
        click(page, "button[data-a=session-add-ex]")
        h = page.locator("#pick-pat").bounding_box()["height"]; assert h >= 40, h; ok(f"picker filters not clipped ({h:.0f}px)")
        page.select_option("#pick-pat", "HPULL"); page.wait_for_timeout(100)
        n1 = page.locator("#picklist button").count()
        page.select_option("#pick-mus", "LAT"); page.wait_for_timeout(100)
        n2 = page.locator("#picklist button").count()
        page.fill("#pickq", "one-arm"); page.wait_for_timeout(100)
        n3 = page.locator("#picklist button").count()
        print("filters HPULL / +LAT / +'one-arm':", n1, n2, n3, page.locator("#pick-count").inner_text())
        assert n1 > n2 > n3 > 0; ok("movement + muscle + search filters combine")
        click(page, "button[data-a=pick-clear]")
        assert page.locator("#picklist button").count() > 150; ok("clear filters")
        page.select_option("#pick-mus", "BI"); page.wait_for_timeout(100)
        names = page.locator("#picklist .name").all_inner_texts(); print("biceps only:", len(names), names[:3])
        assert all("ugin" in x.lower() or "curl" in x.lower() or "chin" in x.lower() or "podciąg" in x.lower() for x in names); ok("muscle filter uses main muscles")
        page.screenshot(path=f"{SHOTS}/11-picker.png")
        click(page, "button[data-a=sheet-close]"); click(page, "button[data-a=discard]"); click(page, "button[data-a=confirm-yes]")

        # ---------- v0.5.4 timer countdown ----------
        page.evaluate("() => { window.__osc = 0; const P = window.AudioContext.prototype; const o = P.createOscillator; P.createOscillator = function () { window.__osc++; return o.apply(this, arguments); }; }")
        click(page, "button[data-a=nav][data-v=today]"); click(page, "button[data-a=start-free]")
        click(page, "button[data-a=session-add-ex]"); page.fill("#pickq", "leg extension"); page.wait_for_timeout(150); click(page, "#picklist button[data-v=leg-extension]")
        st = page.locator(".ex-card").first.locator(".set").first
        st.locator("input[data-k=weight]").fill("50"); st.locator("input[data-k=reps]").fill("12"); st.locator("button.check").click(); page.wait_for_timeout(150)
        page.evaluate("window.Repsmith.S.timer.endAt = Date.now() + 6200; window.Repsmith.S.timer.total = 7")
        page.wait_for_timeout(7000)
        big = page.locator("#tbig").inner_text(); lbl = page.locator("#tlbl").inner_text(); osc = page.evaluate("window.__osc")
        print("timer at end:", big, "|", lbl, "| oscillators:", osc)
        assert big == "0:00" and "KONIEC" in lbl.upper(); ok("timer stops at 0:00 with 'Koniec przerwy' (no negative count)")
        assert osc == 7, osc; ok("5 countdown ticks + 2-tone end sound")
        page.wait_for_timeout(4500)
        assert page.locator("#timer").count() == 0; ok("timer hides after the end")
        click(page, "button[data-a=discard]"); click(page, "button[data-a=confirm-yes]")

        # ---------- v0.5.6 body map ----------
        click(page, "button[data-a=nav][data-v=today]"); click(page, "button[data-a=start-free]")
        click(page, "button[data-a=session-add-ex]")
        assert page.locator(".sheet .bodymap").count() == 1; ok("body map in exercise picker")
        page.locator(".sheet .bodymap [data-m=CH]").first.click(); page.wait_for_timeout(150)
        names = page.locator("#picklist .name").all_inner_texts()
        sel = page.locator("#pick-mus").input_value()
        print("tap chest ->", sel, len(names), names[:3])
        ids = page.locator("#picklist button").evaluate_all("els => els.map(e => e.dataset.v)")
        allch = page.evaluate("ids => ids.every(id => window.Repsmith.S.ex.get(id).primary.includes('CH'))", ids)
        assert sel == "CH" and page.locator(".sheet .bodymap .bm-m.on").count() >= 2 and allch; ok("tap chest filters to chest exercises and highlights both pecs")
        page.screenshot(path=f"{SHOTS}/12-picker-body.png")
        page.locator(".sheet .bodymap [data-m=CH]").first.click(); page.wait_for_timeout(150)
        assert page.locator("#pick-mus").input_value() == ""; ok("tap again clears muscle filter")
        page.locator(".sheet .bodymap [data-m=TRI]").first.click(); page.wait_for_timeout(150)
        tri = page.locator("#picklist .name").all_inner_texts(); print("triceps:", len(tri), tri[:3])
        assert len(tri) >= 8; ok("tap triceps on back view")
        click(page, "button[data-a=sheet-close]"); click(page, "button[data-a=discard]"); click(page, "button[data-a=confirm-yes]")
        click(page, "button[data-a=nav][data-v=library]")
        page.fill("#libq", ""); page.wait_for_timeout(100)
        click(page, "button[data-a=lib-clear]") if page.locator("button[data-a=lib-clear]").count() else None
        click(page, "#liblist button[data-v=chest-supported-t-bar-row]")
        on = page.locator(".sheet .bodymap .bm-m.on").evaluate_all("els => [...new Set(els.map(e => e.dataset.m))]")
        sec = page.locator(".sheet .bodymap .bm-m.sec").evaluate_all("els => [...new Set(els.map(e => e.dataset.m))]")
        print("detail primary", on, "secondary", sec)
        assert set(on) == {"UB", "LAT"} and set(sec) == {"BI", "RD"}; ok("exercise detail highlights primary/secondary")
        page.screenshot(path=f"{SHOTS}/13-detail-body.png")
        click(page, "button[data-a=sheet-close]")
        click(page, "button[data-a=nav][data-v=progress]"); click(page, "button[data-a=prog-tab][data-v=strength]")
        heat = page.locator(".bodymap .bm-m[class*=' h']").count(); print("heat regions:", heat)
        assert heat > 0; ok("weekly volume heat map")
        page.locator(".bodymap [data-m=Q]").first.click(); page.wait_for_timeout(100)
        tip = page.locator("#bm-tip").inner_text(); print("heat tip:", tip)
        assert "czworogłowe" in tip; ok("tap muscle on heat map shows sets")

        # English
        click(page, "button[data-a=settings]"); click(page, "button[data-a=lang][data-v=en]"); click(page, "button[data-a=sheet-close]")
        click(page, "button[data-a=nav][data-v=today]")
        print("MAIN:", page.locator("main").inner_text()[:300].replace("\n"," | "))
        assert "START WORKOUT" in page.locator("main").inner_text().upper(); ok("English UI")
        # overflow check at 360px
        page.set_viewport_size({"width": 360, "height": 780})
        click(page, "button[data-a=nav][data-v=today]")
        click(page, "button[data-a=pick-day] >> text=Dzień A · Przysiad")
        click(page, "button[data-a=start-day]")
        page.locator(".ex-card").first.locator(".set").first.locator("button.check").click(); page.wait_for_timeout(200)
        sw = page.evaluate("document.documentElement.scrollWidth")
        assert sw <= 360, sw; ok("no horizontal overflow at 360px in workout")
        page.screenshot(path=f"{SHOTS}/07-workout-360-en.png")
        for exid in ["chest-supported-t-bar-row","leg-extension","bench-press","dumbbell-lateral-raise","bayesian-curl","squat","lat-pulldown","romanian-deadlift","hip-adduction-machine","triceps-pushdown"]:
            print(exid, "->", page.evaluate(f"window.Repsmith.substitutes('{exid}').map(c=>c.name_en)"))
        b.close()
finally:
    srv.terminate()
print("ERRORS:", errors)
