import os as _os, tempfile as _tf, subprocess, sys, time
from playwright.sync_api import sync_playwright
_APP = _os.path.abspath(_os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "..", ".."))
_OUT = _os.path.join(_tf.gettempdir(), "repsmith-shots"); _os.makedirs(_OUT, exist_ok=True)
srv = subprocess.Popen([sys.executable, "-m", "http.server", "8776", "-d", _APP], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL); time.sleep(1)
P = F = 0; errs = []
def ok(c, m):
    global P, F
    if c: P += 1; print("PASS", m)
    else: F += 1; print("FAIL", m)
def click(p, s): p.locator(s).first.click(); p.wait_for_timeout(120)
def noov(p, m):
    r = p.evaluate("()=>[document.documentElement.scrollWidth,innerWidth]"); ok(r[0] <= r[1], f"no overflow {m} {r}")
def sheet(p): return p.locator("#sheet").inner_text()
def main(p): return p.locator("main").inner_text()
def fill(p, sel, v): p.locator(sel).fill(v); p.locator(sel).dispatch_event("input"); p.wait_for_timeout(50)
def add_sessions(p, n, tpid):
    p.evaluate("""([n, id]) => { const R = window.Repsmith, S = R.S; const tp = S.templates.find(x => x.id === id);
      for (let i = 0; i < n; i++) { const at = Date.now() - (n - i) * 1000; S.sessions.push({ id: 'x' + Math.random(), name: 'x', templateId: id, dayId: tp.days[i % tp.days.length].id, startedAt: at, endedAt: at + 1800e3, items: [] }); }
      R.persist('sessions'); R.render(); }""", [n, tpid]); p.wait_for_timeout(100)
try:
  with sync_playwright() as pw:
    b = pw.chromium.launch(); ctx = b.new_context(viewport={"width": 360, "height": 780}, device_scale_factor=2, locale="pl-PL", has_touch=True)
    p = ctx.new_page()
    p.on("pageerror", lambda e: errs.append(str(e))); p.on("console", lambda m: errs.append(m.text) if m.type == "error" else None)
    p.goto("http://localhost:8776/index.html"); p.wait_for_selector("text=Dziś trening"); click(p, "button[data-a=intro-ok]")

    # ---------- custom simple plan -> fixed cycle ----------
    click(p, "button[data-a=nav][data-v=plans]"); click(p, "button[data-a=new-plan]"); click(p, "button[data-a=np-create][data-v=simple]")
    p.wait_for_selector("#pickq"); p.fill("#pickq", "squat"); p.wait_for_timeout(150); click(p, "#picklist button[data-v=squat]")
    click(p, "button[data-a=item-save]")
    tpid = p.evaluate("() => window.Repsmith.S.templates[0].id")
    ok("powtarzany tydzień · bez deloadu" in main(p).lower(), "plan shows cycle card: repeating, no deload")
    ok(p.locator("button[data-a=wk-open]").count() == 0, "no weeks editor for repeating plans")
    click(p, "button[data-a=cyc-open]")
    ok("Cykl planu" in sheet(p) or "CYKL PLANU" in sheet(p), "cycle sheet opens")
    click(p, "button[data-a=cyc-type][data-v=fixed]")
    fill(p, "#cy-weeks", "6")
    click(p, "button[data-a=cyc-dl][data-v=weeks]")
    ok(p.locator("button[data-a=cyc-dlw]").count() == 6, "week chips follow the typed number of weeks")
    click(p, "button[data-a=cyc-dlw][data-v='3']"); click(p, "button[data-a=cyc-dlw][data-v='6']")
    p.screenshot(path=f"{_OUT}/20-cycle.png"); noov(p, "cycle sheet")
    fill(p, "#cy-weeks", "30"); click(p, "button[data-a=cyc-save]")
    ok("od 2 do 24" in sheet(p), "weeks out of range rejected")
    fill(p, "#cy-weeks", "6"); fill(p, "#cy-load", "50"); click(p, "button[data-a=cyc-save]")
    ok("0-30%" in sheet(p), "load cut over 30% rejected")
    fill(p, "#cy-load", "10"); click(p, "button[data-a=cyc-save]")
    c = p.evaluate(f"() => window.Repsmith.S.templates.find(x => x.id === '{tpid}').cycle")
    ok(c and c["type"] == "fixed" and c["weeks"] == 6 and c["deload"]["weeks"] == [3, 6] and c["deload"]["sets"] == 40 and c["deload"]["load"] == 10, f"cycle saved {c and c['deload']}")
    tx = main(p).lower()
    ok("6 tygodni" in tx and "tydzień 1 z 6" in tx and "tydz. 3, 6" in tx, "summary: 6 weeks, week 1 of 6, deload 3, 6")
    ok(p.locator("button[data-a=pw-pick]").count() == 6 and p.locator("button[data-a=pw-pick].dl").count() == 2, "preview week chips with deload marks")

    # ---------- weeks editor ----------
    click(p, "button[data-a=edit-item]")
    ok(p.locator("button[data-a=wk-open]").count() == 1, "fixed plan: item sheet has the weeks button")
    click(p, "button[data-a=wk-open]")
    ok(p.locator(".wk-r:not(.wk-h)").count() == 6 and p.locator(".wk-r.dl").count() == 2, "weeks table: 6 rows, 2 deload")
    ok(p.locator(".wk-h span").count() == 3, "simple plan: columns sets + reps only")
    fill(p, "#wg-a", "3"); fill(p, "#wg-b", "5"); click(p, "button[data-a=wg-apply]")
    vals = [p.locator(f"input[data-f=wk][data-w='{w}'][data-k=sets]").input_value() for w in range(1, 7)]
    ok(vals == ["3", "4", "", "4", "5", ""], f"generator fills non-deload weeks evenly: {vals}")
    p.screenshot(path=f"{_OUT}/21-weeks.png"); noov(p, "weeks sheet")
    r2 = p.locator("input[data-f=wk][data-w='2'][data-k=reps]"); r2.fill(""); r2.type("4-6x"); p.wait_for_timeout(50)
    ok(r2.input_value() == "4-6", f"reps field sanitized: {r2.input_value()}")
    fill(p, "input[data-f=wk][data-w='5'][data-k=reps]", "0")
    click(p, "button[data-a=wk-done]")
    ok("Tydzień 5" in sheet(p), "invalid reps rejected with week number")
    fill(p, "input[data-f=wk][data-w='5'][data-k=reps]", "3"); fill(p, "input[data-f=wk][data-w='4'][data-k=sets]", "0")
    click(p, "button[data-a=wk-done]")
    ok("Zmienione: 3 tygodnie" in sheet(p), "back on item sheet with the count of changed weeks")
    click(p, "button[data-a=item-save]")
    wk = p.evaluate(f"() => window.Repsmith.S.templates.find(x => x.id === '{tpid}').days[0].items[0].wk")
    ok(wk and wk["2"] == {"sets": 4, "reps": "4-6"} and wk["4"] == {"sets": 0} and wk["5"] == {"sets": 5, "reps": "3"} and "3" not in wk and "1" not in wk, f"week overrides stored {wk}")
    click(p, "button[data-a=pw-pick][data-v='5']")
    ok("5 × 3" in main(p), "preview week 5 shows 5 × 3")
    click(p, "button[data-a=pw-pick][data-v='4']")
    ok("pominięte w tym tygodniu" in main(p), "week 4 shows the exercise as skipped")
    p.screenshot(path=f"{_OUT}/22-plan-fixed.png"); noov(p, "plan fixed")

    # ---------- why sheet ----------
    click(p, "button[data-a=pw-pick][data-v='1']"); click(p, "button[data-a=why-open][data-v=vol]")
    st = sheet(p)
    ok("Schoenfeld" in st and "Baz-Valle" in st and "Bell" in st and p.locator(".why-src a").count() >= 12, f"sources sheet with links ({p.locator('.why-src a').count()})")
    ok(p.locator(".why-src a[href^='https://doi.org/10.1080/02640414.2016.1210197']").count() == 1, "Schoenfeld DOI link")
    p.screenshot(path=f"{_OUT}/23-why.png"); noov(p, "why sheet")
    click(p, "button[data-a=sheet-close]")
    click(p, "button[data-a=cyc-open]"); click(p, "button[data-a=why-open][data-v=deload]"); click(p, "button[data-a=sheet-close]")
    ok(p.locator("button[data-a=cyc-save]").count() == 1, "closing sources returns to the cycle sheet")
    click(p, "button[data-a=sheet-close]")

    # ---------- training through the cycle ----------
    p.evaluate(f"() => {{ const S = window.Repsmith.S; S.settings.activeTemplateId = '{tpid}'; S.templates.find(x => x.id === '{tpid}').cycle.start -= 864e5; window.Repsmith.render(); }}")
    click(p, "button[data-a=nav][data-v=today]")
    ok("tydzień 1 z 6" in main(p).lower(), "Today shows week 1 of 6")
    add_sessions(p, 2, tpid)
    tx = main(p).lower()
    ok("tydzień 3 z 6" in tx and "deload: serie −40%, ciężar −10%" in tx, "week 3: deload label with sets and load")
    click(p, "button[data-a=start-day]"); p.wait_for_timeout(200)
    a = p.evaluate("() => { const A = window.Repsmith.S.active; return { n: A.items[0].sets.filter(x => x.kind === 'work').length, notes: A.notes, wk: A.week }; }")
    ok(a["n"] == 2 and a["wk"]["deload"] and any("−10%" in x for x in a["notes"]), f"deload session: 3 sets -40% = 2, load note {a}")
    click(p, "button[data-a=discard]"); click(p, "button[data-a=confirm-yes]")
    add_sessions(p, 1, tpid)
    click(p, "button[data-a=nav][data-v=today]")
    ok("tydzień 4 z 6" in main(p).lower() and "Przysiad" not in main(p), "week 4: skipped exercise not listed")
    add_sessions(p, 3, tpid)
    tx = main(p)
    ok("Plan zakończony".lower() in tx.lower() and p.locator("button[data-a=start-day]").count() == 0, "after the last week: plan finished card, no start button")
    p.screenshot(path=f"{_OUT}/24-finished.png")
    click(p, "button[data-a=cyc-again]")
    ok("tydzień 1 z 6" in main(p).lower(), "repeat block -> week 1")

    # ---------- strength block from the library ----------
    click(p, "button[data-a=nav][data-v=plans]"); click(p, "button[data-a=nav][data-v=planlib]")
    click(p, "button[data-a=plib-goal][data-v=Peak]")
    ok(p.locator("button[data-a=plib-open]").count() == 3, "library: 3 strength blocks")
    click(p, "button[data-a=plib-open][data-v=PEAK-12]")
    tx = main(p)
    ok("1RM" in tx and p.locator("button[data-a=pw-pick]").count() == 12 and p.locator("button[data-a=pw-pick].dl").count() == 2, "preview: 1RM note, 12 week chips, 2 deloads")
    click(p, "button[data-a=pw-pick][data-v='12']")
    ok("3 × 1 @90%" in main(p), "preview week 12: test singles at 90%")
    p.screenshot(path=f"{_OUT}/25-peak-prev.png"); noov(p, "peak preview")
    click(p, "button[data-a=plib-use]")
    tp2 = p.evaluate("() => window.Repsmith.S.settings.activeTemplateId")
    ok("tydzień 1 z 12" in main(p).lower() and "@67,5%" in main(p), "Today: week 1 of 12, % targets")
    p.evaluate("() => { const S = window.Repsmith.S; S.maxes.squat = { kg: 200, at: Date.now() }; S.maxes['bench-press'] = { kg: 120, at: Date.now() }; window.Repsmith.persist('maxes'); }")
    click(p, "button[data-a=start-day]"); click(p, "button[data-a=ready-pick][data-v='']"); p.wait_for_timeout(200)
    sq = p.evaluate("() => window.Repsmith.S.active.items.find(i => i.exId === 'squat').sug")
    ok(sq and sq["load"] == 135, f"squat week 1 = 67.5% of 200 = 135: {sq and sq['load']}")
    click(p, "button[data-a=discard]"); click(p, "button[data-a=confirm-yes]")
    # jump to week 12 and test
    p.evaluate(f"() => {{ const tp = window.Repsmith.S.templates.find(x => x.id === '{tp2}'); tp.cycle.shift = 11; window.Repsmith.render(); }}")
    click(p, "button[data-a=nav][data-v=today]")
    ok("tydzień 12 z 12" in main(p).lower(), "shifted to week 12")
    click(p, "button[data-a=start-day]"); click(p, "button[data-a=ready-pick][data-v='']"); p.wait_for_timeout(200)
    t12 = p.evaluate("() => window.Repsmith.S.active.items.map(i => [i.exId, !!i.test, (i.cues || []).join(' ').slice(0, 9), i.sug && i.sug.load])")
    ok(any(x[0] == "squat" and x[1] and x[2].startswith("Test 1RM") and x[3] == 180 for x in t12), f"week 12 squat is a test item at 90%: {t12}")
    ok(not any(x[0] == "barbell-row" for x in t12), "accessory dropped in the test week")
    card = p.locator(".ex-card").first
    s0 = card.locator(".set:not(.warmup)").filter(has=p.locator("input[data-k=weight]"))
    # fill the first work set: 210 x 1
    ws = p.evaluate("() => window.Repsmith.S.active.items[0].sets.findIndex(x => x.kind !== 'warmup')")
    st = card.locator(".set").nth(ws); st.locator("input[data-k=weight]").fill("210"); st.locator("input[data-k=reps]").fill("1"); st.locator("button.check").click(); p.wait_for_timeout(100)
    click(p, "button[data-a=finish]"); click(p, "button[data-a=summary-save]"); p.wait_for_timeout(300)
    p.evaluate(f"() => {{ const tp = window.Repsmith.S.templates.find(x => x.id === '{tp2}'); tp.cycle.shift = 12; window.Repsmith.render(); }}")
    click(p, "button[data-a=nav][data-v=today]")
    tx = main(p)
    ok("wyniki testu 1rm" in tx.lower() and "210 kg" in tx and "teraz 200 kg" in tx, "finished: test result 210 vs current 200")
    p.screenshot(path=f"{_OUT}/26-test.png"); noov(p, "test results")
    click(p, "button[data-a=test-save][data-v=squat]")
    ok(p.evaluate("() => window.Repsmith.S.maxes.squat.kg") == 210, "new squat max saved")
    b.close()
finally: srv.terminate()
real = [e for e in errs if 'ERR_TUNNEL' not in e and 'fonts' not in e]
print("ERRORS:", real); print(f"{P} pass, {F} fail")
